version: "3.9"

services:
  api:
    build: .
    container_name: marketplace_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: appdb
      DB_USER: user
      DB_PASS: pass
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: marketplace_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql